// Mocks generated by Mockito 5.4.2 from annotations
// in privacyidea_authenticator/test/state_notifiers/token_folder_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:privacyidea_authenticator/interfaces/repo/token_folder_repository.dart'
    as _i2;
import 'package:privacyidea_authenticator/model/token_folder.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TokenFolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenFolderRepository extends _i1.Mock
    implements _i2.TokenFolderRepository {
  MockTokenFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TokenFolder>> saveOrReplaceFolders(
          List<_i4.TokenFolder>? folders) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOrReplaceFolders,
          [folders],
        ),
        returnValue:
            _i3.Future<List<_i4.TokenFolder>>.value(<_i4.TokenFolder>[]),
      ) as _i3.Future<List<_i4.TokenFolder>>);
  @override
  _i3.Future<List<_i4.TokenFolder>> loadFolders() => (super.noSuchMethod(
        Invocation.method(
          #loadFolders,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.TokenFolder>>.value(<_i4.TokenFolder>[]),
      ) as _i3.Future<List<_i4.TokenFolder>>);
  @override
  _i3.Future<List<_i4.TokenFolder>> deleteFolders(
          List<_i4.TokenFolder>? folders) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolders,
          [folders],
        ),
        returnValue:
            _i3.Future<List<_i4.TokenFolder>>.value(<_i4.TokenFolder>[]),
      ) as _i3.Future<List<_i4.TokenFolder>>);
}
