analyzer:
  errors:
    constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_string_escapes: false
    unnecessary_string_interpolations: false