// Mocks generated by Mockito 5.4.6 from annotations
// in privacyidea_authenticator/test/unit_test/utils/views/container_view/container_widgets/buttons/rollover_container_tokens_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:basic_utils/basic_utils.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:privacyidea_authenticator/model/container_policies.dart' as _i9;
import 'package:privacyidea_authenticator/model/enums/algorithms.dart' as _i6;
import 'package:privacyidea_authenticator/model/enums/ec_key_algorithm.dart'
    as _i5;
import 'package:privacyidea_authenticator/model/enums/rollout_state.dart'
    as _i7;
import 'package:privacyidea_authenticator/model/enums/sync_state.dart' as _i8;
import 'package:privacyidea_authenticator/model/token_container.dart' as _i2;
import 'package:privacyidea_authenticator/model/tokens/token.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TokenContainerFinalizedCopyWith_2<$Res> extends _i1.SmartFake
    implements _i2.$TokenContainerFinalizedCopyWith<$Res> {
  _Fake$TokenContainerFinalizedCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeToken_3 extends _i1.SmartFake implements _i3.Token {
  _FakeToken_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TokenContainerFinalized].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenContainerFinalized extends _i1.Mock
    implements _i2.TokenContainerFinalized {
  MockTokenContainerFinalized() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get issuer =>
      (super.noSuchMethod(
            Invocation.getter(#issuer),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#issuer),
            ),
          )
          as String);

  @override
  String get nonce =>
      (super.noSuchMethod(
            Invocation.getter(#nonce),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#nonce),
            ),
          )
          as String);

  @override
  DateTime get timestamp =>
      (super.noSuchMethod(
            Invocation.getter(#timestamp),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#timestamp)),
          )
          as DateTime);

  @override
  Uri get serverUrl =>
      (super.noSuchMethod(
            Invocation.getter(#serverUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#serverUrl)),
          )
          as Uri);

  @override
  String get serial =>
      (super.noSuchMethod(
            Invocation.getter(#serial),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serial),
            ),
          )
          as String);

  @override
  _i5.EcKeyAlgorithm get ecKeyAlgorithm =>
      (super.noSuchMethod(
            Invocation.getter(#ecKeyAlgorithm),
            returnValue: _i5.EcKeyAlgorithm.brainpoolp160r1,
          )
          as _i5.EcKeyAlgorithm);

  @override
  _i6.Algorithms get hashAlgorithm =>
      (super.noSuchMethod(
            Invocation.getter(#hashAlgorithm),
            returnValue: _i6.Algorithms.SHA1,
          )
          as _i6.Algorithms);

  @override
  bool get sslVerify =>
      (super.noSuchMethod(Invocation.getter(#sslVerify), returnValue: false)
          as bool);

  @override
  String get serverName =>
      (super.noSuchMethod(
            Invocation.getter(#serverName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serverName),
            ),
          )
          as String);

  @override
  _i7.FinalizationState get finalizationState =>
      (super.noSuchMethod(
            Invocation.getter(#finalizationState),
            returnValue: _i7.FinalizationState.notStarted,
          )
          as _i7.FinalizationState);

  @override
  _i8.SyncState get syncState =>
      (super.noSuchMethod(
            Invocation.getter(#syncState),
            returnValue: _i8.SyncState.notStarted,
          )
          as _i8.SyncState);

  @override
  _i9.ContainerPolicies get policies =>
      (super.noSuchMethod(
            Invocation.getter(#policies),
            returnValue: _i4.dummyValue<_i9.ContainerPolicies>(
              this,
              Invocation.getter(#policies),
            ),
          )
          as _i9.ContainerPolicies);

  @override
  bool get initSynced =>
      (super.noSuchMethod(Invocation.getter(#initSynced), returnValue: false)
          as bool);

  @override
  String get publicClientKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicClientKey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#publicClientKey),
            ),
          )
          as String);

  @override
  String get privateClientKey =>
      (super.noSuchMethod(
            Invocation.getter(#privateClientKey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#privateClientKey),
            ),
          )
          as String);

  @override
  String get $type =>
      (super.noSuchMethod(
            Invocation.getter(#$type),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#$type),
            ),
          )
          as String);

  @override
  _i2.$TokenContainerFinalizedCopyWith<_i2.TokenContainerFinalized>
  get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue:
                _Fake$TokenContainerFinalizedCopyWith_2<
                  _i2.TokenContainerFinalized
                >(this, Invocation.getter(#copyWith)),
          )
          as _i2.$TokenContainerFinalizedCopyWith<_i2.TokenContainerFinalized>);

  @override
  Uri get registrationUrl =>
      (super.noSuchMethod(
            Invocation.getter(#registrationUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#registrationUrl)),
          )
          as Uri);

  @override
  Uri get challengeUrl =>
      (super.noSuchMethod(
            Invocation.getter(#challengeUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#challengeUrl)),
          )
          as Uri);

  @override
  Uri get syncUrl =>
      (super.noSuchMethod(
            Invocation.getter(#syncUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#syncUrl)),
          )
          as Uri);

  @override
  Uri get transferUrl =>
      (super.noSuchMethod(
            Invocation.getter(#transferUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#transferUrl)),
          )
          as Uri);

  @override
  Uri get unregisterUrl =>
      (super.noSuchMethod(
            Invocation.getter(#unregisterUrl),
            returnValue: _FakeUri_1(this, Invocation.getter(#unregisterUrl)),
          )
          as Uri);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.TokenContainer withClientKeyPair(
    _i10.AsymmetricKeyPair<_i10.ECPublicKey, _i10.ECPrivateKey>? keyPair,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withClientKeyPair, [keyPair]),
            returnValue: _i4.dummyValue<_i2.TokenContainer>(
              this,
              Invocation.method(#withClientKeyPair, [keyPair]),
            ),
          )
          as _i2.TokenContainer);

  @override
  String signMessage(String? msg) =>
      (super.noSuchMethod(
            Invocation.method(#signMessage, [msg]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#signMessage, [msg]),
            ),
          )
          as String);

  @override
  String? trySignMessage(String? msg) =>
      (super.noSuchMethod(Invocation.method(#trySignMessage, [msg]))
          as String?);

  @override
  _i3.Token addOriginToToken({required _i3.Token? token, String? tokenData}) =>
      (super.noSuchMethod(
            Invocation.method(#addOriginToToken, [], {
              #token: token,
              #tokenData: tokenData,
            }),
            returnValue: _FakeToken_3(
              this,
              Invocation.method(#addOriginToToken, [], {
                #token: token,
                #tokenData: tokenData,
              }),
            ),
          )
          as _i3.Token);
}
