name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_messaging:
    path: ../
  flutter:
    sdk: flutter
  flutter_local_notifications: ^3.0.0
  http: ^0.13.0

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web
  firebase_messaging:
    path: ../
  firebase_messaging_platform_interface:
    path: ../../firebase_messaging_platform_interface
  firebase_messaging_web:
    path: ../../firebase_messaging_web
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
