#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/frankmerkel/src/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/frankmerkel/Documents/GitHub/pi-authenticator"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/mains/main_netknights.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=4.3.0"
export "FLUTTER_BUILD_NUMBER=403003"
export "DART_DEFINES=RkxVVFRFUl9BUFBfRkxBVk9SPW5ldGtuaWdodHM="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/frankmerkel/Documents/GitHub/pi-authenticator/.dart_tool/package_config.json"
export "FLAVOR=netknights"
