name: Flutter Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.44.0"
          cache: true

      - name: Cache Flutter Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Clean Flutter project
        run: flutter clean

      - name: Display Flutter version
        run: flutter --version

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Run Flutter tests
        run: flutter test --no-pub
